<?php

namespace Alegra\Controller;

use Alegra\Hydrator\ProductHydrator;
use Alegra\Model\Product;
use Alegra\Model\ProductCommandInterface;
use Alegra\Model\ProductRepositoryInterface;
use Zend\Mvc\Controller\AbstractRestfulController;
use Zend\View\Model\JsonModel;

class ProductController extends AbstractRestfulController
{
	/**
     * @var ProductRepositoryInterface
     */
    private $productRepository;
    private $productCommand;

    public function __construct(
            ProductRepositoryInterface $productRepository, 
            ProductCommandInterface $productCommand
        )
    {
        $this->productRepository = $productRepository;
        $this->productCommand = $productCommand;
    }

    private function notFound()
    {
        $this->getResponse()->setStatusCode(404);
        return new JsonModel([
            'success' => false,
            'message' => 'Not found'
        ]);
    }


    public function getList()
    {
        $products = $this->productRepository->findAllProducts();
        //var_dump($products);
        $test = $products->toArray();
        $json = new JsonModel([
            'success' => true,
            'data' => $products->toArray()
        ]);
        //var_dump($json);
        return $json;
    }


    public function get($id)
    {

        $product = $this->productRepository->findProduct($id);

        if ($product instanceof Product) {
            $arreglo = $product->toArray();
            return new JsonModel([
                'success' => true,
                'data' => $product->toArray()
            ]);
        }
        else {
            return $this->notFound(); // Return a 404 if the product is not found
        }
    }

    // POST /product
    // Creates a new product
    // The $data parameter is automatically mapped from the request body
    public function create($data)
    {

        unset($data['id']);

        //$decode = json_decode($data, true);
        $decode = $this->array_filter_recursive($data);

        if (! $decode)
            return $this->notFound();

        $hydrator = new  ProductHydrator();
        $product = $hydrator->hydrate( $decode,new Product());

        $enviar = $this->productCommand->insertPost($product);

        if ($enviar instanceof Product) {
            $arreglo = $enviar->toArray();
            return new JsonModel([
                'success' => true,
                'data' => $arreglo
            ]);
        }
        else {
            return $this->notFound(); // Return a 404 if the product is not found
        }

        $this->getResponse()->setStatusCode(200);

        return new JsonModel([
            'success' => true,
            'message' => 'Success',
            'data' => $enviar->toArray()
         ]);
    }

    public function delete($id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }

    public function update($id, $data)
    {
        $resource = $id;

        return parent::update($id, $data); // TODO: Change the autogenerated stub
    }


    public function ConverCurrency()
    {
        // set API Endpoint, access key, required parameters
            $endpoint = 'live';
            $access_key = '697bee86c1bd1128bf49fe7270dfbb97';

            $currencies = 'COP';

            // initialize CURL:
            $ch = curl_init('http://apilayer.net/api/'.$endpoint.'?access_key='.$access_key.'&currencies='.$currencies.'');
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

            // get the (still encoded) JSON data:
            $json = curl_exec($ch);
            curl_close($ch);

            // Decode JSON response:
            $conversionResult = json_decode($json, true);

            // access the conversion result
            return $conversionResult['result'];
    }

    function array_filter_recursive($input)
    {
        foreach ($input as &$value)
        {
            if (is_array($value))
            {
                $value = $this->array_filter_recursive($value);
            }
        }

        return array_filter($input);
    }
 
}