<?php
/**
 * Created by PhpStorm.
 * User: brodriguez
 * Date: 01/04/18
 * Time: 07:48 PM
 */

namespace Alegra\Utility;

use Zend\I18n\Translator\Translator;


class MyTranslator extends Translator
{
    public static function factory($options)
    {
        return parent::factory($options); // TODO: Change the autogenerated stub
    }

    public function reloadMessages($textDomain, $locale)
    {
         unset($this->messages[$textDomain]);
        $this->loadMessages($textDomain,$locale);

    }
}