<?php
/**
 * Created by PhpStorm.
 * User: brodriguez
 * Date: 31/03/18
 * Time: 07:25 PM
 */

namespace Alegra\Utility;

use Alegra\Factory\DatabaseTranslationLoaderFactory;
use Interop\Container\ContainerInterface;
use Zend\I18n\Translator\LoaderPluginManager;
use Zend\I18n\Translator\TranslatorServiceFactory;
use Zend\ServiceManager\ServiceLocatorInterface;


class MyTranslatorServiceFactory extends TranslatorServiceFactory
{
    // TODO: Change the autogenerated stub
    public function __invoke(ContainerInterface $container, $requestedName, array $options = null)
    {
        // Configure the translator
        $config = $container->get('config');
        $trConfig = isset($config['translator']) ? $config['translator'] : [];
        $translator = MyTranslator::factory($trConfig);
        return $translator;
    }


}